<Project>
    <PropertyGroup Condition="'$(ElinGamePath.Trim())' == '' AND '$(OS)' == 'Windows_NT'">
        <ElinGamePath>E:\SteamLibrary\steamapps\common\Elin</ElinGamePath>
    </PropertyGroup>
    <PropertyGroup>
        <NoWarn>1701;1702;8620;8604</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugType>portable</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'DebugNightly' ">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE;NIGHTLY</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'ReleaseNightly' ">
        <DebugType>portable</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE;NIGHTLY</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="$(ElinGamePath)\BepInEx\core\0Harmony.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\BepInEx\core\BepInEx.Core.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\BepInEx\core\BepInEx.Unity.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\BepInEx\core\Mono*.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\ClassLibrary2.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\DOTween.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\Elin.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\Heathen*.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\com.rlabrecque.steamworks.net.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\LZ4.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\Newtonsoft.Json.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\NPOI*.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\Plugins*.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\Reflex.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\UniTask*.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\UnityEngine*.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\mscorlib.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\netstandard.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\System.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\System.Core.dll">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(ElinGamePath)\Elin_Data\Managed\System.Memory.dll">
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>